# version: '3'
name: nyonyo

services:
  db:
    image: postgres:16-alpine3.19
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nyonyo
    ports:
      - "5453:5432"
    networks:
      - docker
networks: 
  docker: 
    driver: bridge
volumes:
  db-data: